### ISSUE TITLE
sql_type: Number(1) is getting mapped to Boolean

### ISSUE THREAD

**Issue by aninder** [kubo/ruby-oci8#248]
Oracle datatype Number(1) was getting mapped to integer alright when our application was at Rails 3.2 and ruby-oci8 2.2.9 

Upgrading to Rails 5 .2 and ruby-oci8 2.2.11 makes Number(1) mapped to Boolean !

Below is what i have for the column in schema_cache.yml
    ```
name: column1
    table_name: table1
    sql_type_metadata: !ruby/object:ActiveRecord::ConnectionAdapters::OracleEnhanced::TypeMetadata
      delegate_dc_obj: &1734 !ruby/object:ActiveRecord::ConnectionAdapters::SqlTypeMetadata
        sql_type: NUMBER(1)
        type: :boolean
        limit: 
        precision: 
        scale: 
      type_metadata: *1734
      virtual: false
    'null': true
    default: 
    default_function: 
    collation: 
    comment:
```
